webtalk_init -webtalk_dir C:/Users/LOPEZS/Desktop/DL2010_Lopez/Lab05/Lab05.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 20 11:49:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176094205_174126154_210553245_322" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bfcc932f-2b6e-4ade-8dfc-ab63afd9d5ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b4d1040c1814b538b10050cb3c23144" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6636_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2114111776 -regid "176094205_174126154_210553245_322" -xml C:/Users/LOPEZS/Desktop/DL2010_Lopez/Lab05/Lab05.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/LOPEZS/Desktop/DL2010_Lopez/Lab05/Lab05.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/LOPEZS/Desktop/DL2010_Lopez/Lab05/Lab05.sim/sim_1/behav/xsim/xsim.dir/fulladder_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
